version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pg_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/devdb
      PORT: 3001
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  postgres-data: 